# This file is to use service in developer mode
# docker-compose -f ./docker-compose-dev.yml up --build
# We expose 8089 port do you can run flask server manually

version: '2'
services:
  web:
    build:
      context: misc/docker/web
      args:
        GIT_BRANCH: devel
    restart: always
    ports:
    - 80:80
    - 8089:8089
    links:
    - redis
    environment:
    - DB_NAME='chessdb'
    - DB_USER='postgres'
    - DB_PASSWORD='chessdb'
    volumes:
    - /var/run/postgresql:/var/run/postgresql/
  redis:
    image: redis
    restart: always
