# To run it in foreground mode
# docker-compose up --build
# To run it in detached mode
# docker-compose up --build -d

version: '2'
services:
  web:
    build:
      context: misc/docker
      args:
        GIT_BRANCH: mobilecomments
    restart: always
    ports:
    - 80:80
    links:
    - redis
    environment:
    - DB_HOST='172.25.60.138'
    - DB_NAME='postgres'
    - DB_USER='postgres'
  redis:
    image: redis
    restart: always
