# This file is to use service in developer mode
# docker-compose -f ./docker-compose-dev.yml up --build
# We expose 8089 port do you can run flask server manually

version: '2'
services:
  web:
    build:
      context: misc/docker
      args:
        GIT_BRANCH: master
    restart: always
    ports:
    - 80:80
    - 8089:8089
    links:
    - redis
    environment:
    - DB_HOST='10.0.0.4'
    - DB_NAME='postgres'
    - DB_USER='postgres'
  redis:
    image: redis
    restart: always
